version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:16.5.0-buster-slim
  resource_class: small

jobs:
  npm-install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm install
          command: | 
            npm install
            npm install --no-save
      - persist_to_workspace:
          root: .
          paths:
             - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: eslint . --ext .ts
  
  webpack:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build-main
          command: npx webpack
      - store_artifacts:
          path: /root/repo/dist/

  build-test-apps:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build test apps
          command: npx webpack -c tests/test-apps/webpack.config.js || true
      - store_artifacts:
          path: /root/repo/tests/test-apps/bundles/

  browser-tests:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Fix weird firefox issue
          command: |
            cd /
            yes | npx playwright
            cd /root/repo/
          
      - run:
          name: Run Tests
          command: |
            npm install -D @playwright/test
  

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - npm-install
      - webpack:
          requires:
            - npm-install
